name: emeraldjava.github.io
markdown: redcarpet
redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables"]
pygments: true
baseurl: /blog
permalink: /blog/:title
auto: true