"use strict"

module.exports = {
  url: "https://emeraldjava.github.io",
  title: "emeraldjava",
  tagline: "Java, Spring, DevOps experimenter, chasing a marathon and cycling while home brewing and gardening with family.",
  copyright: "© 2019 emeraldjava, All rights reserved",
  author: {
    name: "emeraldjava",
    bio: "Java, Spring, DevOps experimenter chasing a marathon and cycling while home brewing and gardening with family.",
    contacts: {
      linkedin: "https://ie.linkedin.com/in/paultoconnell/",
      github: "https://github.com/emeraldjava",
      stackoverflow: "https://stackoverflow.com/users/55794/emeraldjava",
      freecodecamp: "https://www.freecodecamp.org/",
      twitter: "https://twitter.com/emeraldjava",
    },
  },
  labels: [
    {
      tag: "run",
      tech: "Run",
      name: "FaRunning",
      size: 20,
      color: "red",
    },
    {
      tag: "cycle",
      tech: "Cycle",
      name: "FaBicycle",
      size: 20,
      color: "blue",
    },
    {
      tag: "nodejs",
      tech: "Node.js",
      name: "DiNodejsSmall",
      size: 20,
      color: "lightgreen",
    },
    {
      tag: "git",
      tech: "Git",
      name: "DiGitMerge",
      size: 20,
      color: "white",
    },
    {
      tag: "javascript",
      tech: "JavaScript",
      name: "DiJsBadge",
      size: 20,
      color: "yellow",
    },
    {
      tag: "css",
      tech: "CSS",
      name: "DiCss3Full",
      size: 20,
      color: "teal",
    },
    {
      tag: "beer",
      tech: "Beer",
      name: "FaBeer",
      size: 20,
      color: "deepskyblue",
    },
    {
      tag: "ruby",
      tech: "Ruby",
      name: "DiRuby",
      size: 20,
      color: "crimson",
    },
    {
      tag: "java",
      tech: "Java",
      name: "FaJava",
      size: 20,
      color: "wheat",
    },
    {
      tag: "angular",
      tech: "Angular",
      name: "DiAngularSimple",
      size: 20,
      color: "red",
    },
    {
      tag: "html",
      tech: "HTML",
      name: "FaHtml5",
      size: 20,
      color: "darkorange",
    },
    {
      tag: "php",
      tech: "php",
      name: "DiPhp",
      size: 20,
      color: "violet",
    },
    {
      tag: "mongodb",
      tech: "MongoDB",
      name: "DiMongodb",
      size: 20,
      color: "green",
    },
    {
      tag: "vscode",
      tech: "VS Code",
      name: "DiVisualstudio",
      size: 20,
      color: "deepskyblue",
    },
  ],
}
