baseURL = 'https://emeraldjava.github.io/'
languageCode = 'en-us'
title = 'Posts from emeraldjava'
theme = "github-style"
googleAnalytics = "UA-156016480-1"

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[params]
author = "emeraldjava"
description = "Java, Spring, DevOps experimenter, chasing a marathon and cycling."
github = "emeraldjava"
twitter = "emeraldjava"
linkedin = "paultoconnell"
url = "https://emeraldjava.github.io/"
keywords = "blog, google analytics"
rss = false
lastmod = true
userStatusEmoji = ""
favicon = ""
location = "Ireland"
enableGitalk = false

# https://themes.gohugo.io/themes/github-style/

# https://digitaldrummerj.me/hugo-post-series/
#[taxonomies]
#series = "series"