name: build

on:
  push:
    branches:
      - gatsby

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Deploy with github-pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_REPO }}
          BASE_BRANCH: gatsby # The branch the action should deploy from.
          BRANCH: master # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.
          BUILD_SCRIPT: npm install && npm run-script build